version: 2
jobs:
  build:
    docker:
      - image: node:9.9.0
    working_directory: ~/git/blog.hackbox.link
    steps:
      - checkout
      - run:
          name: Clean Sources List
          command: echo "running: sed -i /jessie-updates/d /etc/apt/sources.list"
          command: sed -i /jessie-updates/d /etc/apt/sources.list
      - run:
          name: Apt-Get Update
          command: apt-get update
      - run:
          name: Install Git
          command: apt-get install -yq git
#      - run:
#          name: Install NodeJS
#          command: apt-get install -y nodejs
#      - run:
#          name: Install Curl
#          command: apt-get install -yq curl
#      - run:
#          name:  Install NVM
#          command: |
#            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
#            source ~/.bashrc
#            which nvm
#            nvm install 9.9.0
##      - run:
##          name: Install Node 9.9.0
##          command: nvm install 9.9.0
      - run:
          name: Install NPM
          command: apt-get install -yq npm
      - run:
          name: Install Python PIP
          command: apt-get install -yq python-pip
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
#      - restore_cache:
#          keys:
#            - npm-deps-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
          command: find /root/.npm/_logs/ -type f -exec cat {} \;
      - run:
          name: Download theme
          command:  git clone https://github.com/klugjo/hexo-theme-alpha-dust themes/alpha-dust
#      - run:
#          name: Install Theme Dependencies
#          command: | 
#            for npm_pack in 'hexo-renderer-pug-loader' 'hexo-renderer-stylus'
#            do  npm install "${npm_pack}" --save
#            done
      - run:
          name: Set theme language
          command: cp -fv themes/alpha-dust/languages/pt.yml themes/alpha-dust/languages/default.yml 
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
#      - run:
#          name: Remove public folder
#          command: |
#            rm -rfv public/*
      - run:
          name: Generate static website
          command: hexo generate
      - run:
          name: Install AWS CLI
          command:  pip install awscli
      - run:
          name: Debug info
          command: |
            cat /etc/os-release
            hexo -v
            node --version
            ls -ltrahR public
            hexo list route
            hexo list post          
      - run:
          name: Push to S3 bucket
          command: cd public/ && aws s3 sync . s3://blog.hackbox.link --no-progress --delete
