version: 2
jobs:
  build:
    docker:
      - image: node:9.9.0
        environment:
          THEME_URL: "https://github.com/klugjo/hexo-theme-alpha-dust"
          THEME_NAME: "alpha-dust"
          OLD_PATTERN: "google_analytics:"
          NEW_PATTERN: "google_analytics: UA-154191934-1"
    working_directory: ~/git/blog.hackbox.link
    steps:
      - checkout
      - run:
          name: Fix Sources List     
          command: sed -i /jessie-updates/d /etc/apt/sources.list
      - run:
          name: Apt-Get Update
          command: apt-get update
      - run:
          name: Install Git
          command: apt-get install -yq git
      - run:
          name: Install Curl
          command: apt-get install -yq curl
#      - run:
#          name: Install NodeJS
#          command: apt-get install -y nodejs
#      - run:
#          name: Install Curl
#          command: apt-get install -yq curl
#      - run:
#          name:  Install NVM
#          command: |
#            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
#            source ~/.bashrc
#            which nvm
#            nvm install 9.9.0
##      - run:
##          name: Install Node 9.9.0
##          command: nvm install 9.9.0
      - run:
          name: Install NPM
          command: apt-get install -yq npm
      - run:
          name: Install Python PIP
          command: apt-get install -yq python-pip
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
#      - restore_cache:
#          keys:
#            - npm-deps-{{ checksum "package.json" }}
#      - run:
#          name: Clean NPM cache
#          command: npm cache clean --force
      - run:
          name: Clean NPM Cache and install dependencies
          command: npm cache clear --force && npm install --no-shrinkwrap --update-binary
#      - run: 
#          name: Debug NPM Install
#          command: find /root/.npm/_logs/ -type f -exec cat {} \;
      - run:
          name: Download theme
          command: git clone $THEME_URL themes/$THEME_NAME
      - run:
          name: Set Google Analytics
          command: sed -i "s/^$OLD_PATTERN.*/$NEW_PATTERN/g" themes/$THEME_NAME/_config.yml
      - run:
          name: Debug Google Analytics
          command: cat themes/$THEME_NAME/_config.yml
      - run:
          name: Download Google Analytics Script
          command: curl https://raw.githubusercontent.com/elisboa/blog.hackbox.link/blog/google_analytics.ejs -o google_analytics.ejs
      - run:
          name: Install Google Analytics Script on theme
          command: cp -uva google_analytics.ejs themes/$THEME_NAME/layout/_partial
      - run:
          name: Install Google Analytics Script on theme failsafe
          command: cp -uva google_analytics.ejs themes/$THEME_NAME/google-analytics.ejs
      - run:
          name: Debug Google Analytics Script
          command: ls -ltrah themes/$THEME_NAME
#      - run:
#          name: Install Theme Dependencies
#          command: | 
#            for npm_pack in 'hexo-renderer-pug-loader' 'hexo-renderer-stylus'
#            do  npm install "${npm_pack}" --save
#            done
      - run:
          name: Set theme language
          command: cp -fv themes/$THEME_NAME/languages/pt.yml themes/$THEME_NAME/languages/default.yml 
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
#      - run:
#          name: Remove public folder
#          command: |
#            rm -rfv public/*
      - run:
          name: Generate static website
          command: hexo generate
      - run:
          name: Install Google Analytics Script on public dir
          command: cp -uva google_analytics.ejs public
      - run:
          name: Install Google Analytics Script on public dir failsafe
          command: cp -uva google_analytics.ejs public/google-analytics.ejs
      - run:
          name: Install Google Analytics Script on public/js dir
          command: cp -uva google_analytics.ejs public/js
      - run:
          name: Install Google Analytics Script on public/js dir failsafe
          command: cp -uva google_analytics.ejs public/js/google-analytics.ejs
      - run:
          name: Install AWS CLI
          command:  pip install awscli
      - run:
          name: Debug info
          command: |
            cat /etc/os-release
            hexo -v
            node --version
            ls -ltrahR public
            hexo list route
            hexo list post
      - run:
          name: Push to S3 bucket
          command: cd public && aws s3 sync . s3://blog.hackbox.link --no-progress --delete
      - run:
          name: Clean cache
          command: aws cloudfront create-invalidation --distribution-id EHKQJRHCFVH2T --paths /*
